### ISSUE TITLE
Provide singleton MNNotificationsManager instance rather than requiring the app developer to hold on to a reference themselves

### ISSUE THREAD

**Issue by atroutt** [mobiquity-networks/MNNotificationsManager-iOS-SDK#1]
Most similar SDKs will provide a singleton instance to the main SDK class rather than requiring the app developer to hold on to a reference themselves. This makes integration cleaner and faster.

Something like

```
[MNNotificationsManager shared] start];
```

This singleton can be used to initialize the app/session and for later start/stop.

Here's an example from the Branch.io SDK docs

```
[[Branch getInstance] initSessionWithLaunchOptions:launchOptions andRegisterDeepLinkHandler:^(NSDictionary *params, NSError *error) {
    if (!error) {
        // ...
    }
}];
```

It's a little work for you guys that makes my life as a developer a lot easier.

**Comment by atroutt** [comment]
I saw this in the getting started docs. I'm really curious as to why.

```
// It is NOT recommended to use the Singleton Pattern to wrap the Notifications Manager
// instance.
```

**Comment by albsala** [comment]
@atroutt thank you for your feedback!

I'm pretty sure we both have read or have been involved in discussions about this singleton pattern / evil anti-pattern :), it is not about work.

We would have problems with clients calling methods before/without init sessions if they can get an unlinked singleton, that's for sure.

But we will think about it for following versions and products, thank you!!

**Comment by albsala** [comment]
@atroutt that comment comes from client support. Some people try to encapsulate the block-based asynchronous instantiation into a singleton, and even _worse_, they try to do it using bad practices. That generates them problems, and also avoid retries and deallocation.

We would be in the same situation with a singleton/initSession approach like you propose.

Again, we will think about it for following versions and products.
