### ISSUE TITLE
I cannot receive a notificaiton from the SDK

### ISSUE THREAD

**Issue by summer9011** [mobiquity-networks/MNNotificationsManager-iOS-SDK#5]
Hi, I'm a developer from HangZhou City, ZheJiang Province, China.

I have a problem after integrated the SDK. 

First, I downloaded a App from App Store, the App can make my phone as a beacon emulator, only need to input my real beacon device's uuid, major, minor informations. Then start the app to advertise. 

Second, I run a test project which integrated the SDK, I accept the location authorization and the bluetooth authorization, and also see this delegate method `- (void)notificationsManager:(MNNotificationsManager *)notificationsManager beaconLocationSignal:(MNNMBeaconLocationSignal *)beaconLocationSignal` received a message and got the beacon info. But cannot receive a notification from the SDK, I ensure phone's notification setting is accepted.

My company setup the beacon information in USA, I try it in China. So is the management system can configure where the notification can be received? I tried it use this demo.

**Comment by dnapolitano** [comment]
I'm sorry that I did not see this sooner. As I think you discovered, you cannot monitor Bluetooth from a simulator. (Simulators don't support Bluetooth.) You'll need, please, to build your project to a physical test device.
